### ISSUE TITLE
im getting API is down notifing users

### ISSUE THREAD

**Issue by ghost** [Hyperclaw79/HyperAI#6]

**Comment by ghost** [comment]
im not good with cleverbot io

**Comment by Hyperclaw79** [comment]
That means, server side error on cleverbot.io.
Just gotta wait till it's fixed.

Make sure all your keys are correct though using their explorer utility
within the documentation.

This code is a sample wrapper that send asynchronous http requests to their
API.

**Comment by ghost** [comment]
thanks

**Comment by Logan-Purcell** [comment]
is it working for you hyperclaw79

**Comment by ghost** [comment]
is it working for you hyperclaw79

**Comment by Hyperclaw79** [comment]
Haven't used it in ages, so not sure. Try it with a different set of api keys.

**Comment by ghost** [comment]
I have but nothing
